name: 'Create Summary Check Status'
description: 'Provide a final check for multiple checks'
author: 'maxisam'
branding:
  icon: check
  color: yellow
inputs:
  jobResults:
    required: true
    description: jobs results with new line as delimiter
    default: ''
  authToken:
    description: 'Use secrets.GITHUB_TOKEN or your own token if you need to trigger other workflows'
    required: true  
  state:
    description: 'The status of the check: success, error, failure or pending (if this is not set, it is in summary mode)'
    default: ''
    required: false
  failureStates:
    description: 'The job results for failure'
    default: |
      failure
      cancelled
    required: false
  checkName:
    description: 'The context, this is displayed as the name of the check'
    default: 'Check Status Summary'
    required: false
  description:
    description: 'Short text explaining the status of the check'
    default: ''
    required: false
  owner:
    description: 'Repostory owner, defaults to context github.repository_owner if omited'
    default: ${{ github.repository_owner }}
    required: false
  repository:
    description: 'Repository, default to context github.repository if omited'
    default: ${{ github.repository }}
    required: false
  sha:
    description: 'SHA of commit to update status on, defaults to context github.sha'
    default: ${{ github.sha }}
    required: false
  targetUrl: 
    description: 'URL/URI to use for further details.'
    required: false

outputs:
  summary:
    description: The result of input state

runs:
  using: 'node16'
  main: 'dist/index.js'
